version: '2.4'
volumes:
  redis-data:
services:
  # Redis
  redis:
    image: redis:5.0.2-alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 10
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - redis-data:/data
  # API
  api:
    build:
      context: .
      dockerfile: Dockerfile
      env_file:
        - .env
    links:
      - redis
    depends_on:
      redis:
        condition: service_healthy
    command: npm start
    environment:
      REDIS_URL: redis://redis:6379
    ports:
      - 0.0.0.0:3000:3000
    healthcheck:
      test: curl -fsSL http://localhost:$$PORT/health_check
      interval: 10s
      timeout: 5s
      retries: 10

